// Auto-generated by run_sanity_sim.sh — do not edit manually.
`define CHUNK_SIG0   "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/chunk_sig0.hex"
`define CHUNK_SIG1   "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/chunk_sig1.hex"
`define CHUNK_SIG2   "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/chunk_sig2.hex"
`define CHUNK_NOISE0 "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/chunk_noise0.hex"
`define WAVE_CSV     "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/sanity_wave.csv"
`define RESULTS_TXT  "/home/work1/Works/HiLoGatedCNNTrigger/hw/sim/sanity_data/sanity_results.txt"
