#!/usr/bin/env bash
# =============================================================================
# run_sanity_sim.sh
#
# End-to-end sanity simulation for HILO_CNN_TRIGGER — no GUI needed.
#
# Steps:
#   1. (optional) Run prepare_sanity_chunks.py to create hex data files.
#   2. Generate sanity_paths.svh (absolute paths for XSim).
#   3. Generate bender source list (bender script vivado -t simulation).
#   4. Compile all HDL sources with xvhdl / xvlog.
#   5. Elaborate with xelab.
#   6. Simulate with xsim --runall.
#   7. Plot results with plot_sanity_results.py.
#
# Usage:
#   cd /path/to/HiLoGatedCNNTrigger
#   source /path/to/Vivado/202X.X/settings64.sh   # puts xvhdl, xsim in PATH
#   bash scripts/run_sanity_sim.sh [--skip-data] [--skip-plot] [--thresh 300]
#
# Options:
#   --skip-data   Skip prepare_sanity_chunks.py (data already exists).
#   --skip-plot   Skip plot_sanity_results.py after simulation.
#   --thresh N    Hi-Lo threshold passed to prepare script (default: 300).
#
# Requirements:
#   - Vivado (any year ≥ 2020) sourced in PATH (xvhdl, xvlog, xelab, xsim)
#   - bender in PATH (https://github.com/pulp-platform/bender)
#   - Python ≥ 3.8 with numpy, matplotlib, pandas  (for data prep + plotting)
# =============================================================================

set -euo pipefail

# ─── Resolve project root (parent of this script's directory) ────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ─── Defaults ─────────────────────────────────────────────────────────────────
SKIP_DATA=0
SKIP_PLOT=0
THRESH=300

# ─── Parse arguments ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-data)  SKIP_DATA=1  ; shift ;;
        --skip-plot)  SKIP_PLOT=1  ; shift ;;
        --thresh)     THRESH="$2"  ; shift 2 ;;
        -h|--help)
            sed -n '/^# Usage:/,/^# ====/p' "$0" | head -20
            exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ─── Derived paths ────────────────────────────────────────────────────────────
DATA_DIR="${ROOT}/hw/sim/sanity_data"
LOG_DIR="${ROOT}/logs/sim"
PATHS_SVH="${DATA_DIR}/sanity_paths.svh"
BENDER_TCL="${LOG_DIR}/bender_sources.tcl"
WORK="xil_defaultlib"
TOP="tb_sanity"
SNAP="tb_sanity_snapshot"

# ─── Utility: print a header ──────────────────────────────────────────────────
hr() { echo ""; echo "──────────────────────────────────────────────────────────────"; }

# ─── Check required tools ────────────────────────────────────────────────────
check_tool() {
    command -v "$1" &>/dev/null || {
        echo "ERROR: '$1' not found in PATH."
        if [[ "$1" == x* ]]; then
            echo "       Source Vivado: source /path/to/Vivado/202X.X/settings64.sh"
        elif [[ "$1" == "bender" ]]; then
            echo "       Install bender: https://github.com/pulp-platform/bender/releases"
        fi
        exit 1
    }
}
check_tool xvhdl
check_tool xvlog
check_tool xelab
check_tool xsim
check_tool bender

mkdir -p "$LOG_DIR" "$DATA_DIR"
cd "$ROOT"

echo "============================================================"
echo "  HILO_CNN_TRIGGER Sanity Simulation"
echo "  Root : $ROOT"
echo "  Data : $DATA_DIR"
echo "  Logs : $LOG_DIR"
echo "============================================================"

# ─── Step 1: Prepare hex data ─────────────────────────────────────────────────
hr
if [[ $SKIP_DATA -eq 1 ]]; then
    echo "[SKIP] Data preparation (--skip-data set)."
    # Verify data exists
    for f in chunk_sig0.hex chunk_sig1.hex chunk_sig2.hex chunk_noise0.hex; do
        [[ -f "${DATA_DIR}/${f}" ]] || {
            echo "ERROR: ${DATA_DIR}/${f} not found."
            echo "       Run without --skip-data or run prepare_sanity_chunks.py manually."
            exit 1
        }
    done
else
    echo "[1/5] Running prepare_sanity_chunks.py ..."
    python3 "${SCRIPT_DIR}/prepare_sanity_chunks.py" \
        --project-root "$ROOT" \
        --thresh "$THRESH"
fi

# ─── Step 2: Generate sanity_paths.svh ───────────────────────────────────────
hr
echo "[2/5] Writing sanity_paths.svh ..."
cat > "$PATHS_SVH" << SVEOF
// Auto-generated by run_sanity_sim.sh — do not edit manually.
\`define CHUNK_SIG0   "${DATA_DIR}/chunk_sig0.hex"
\`define CHUNK_SIG1   "${DATA_DIR}/chunk_sig1.hex"
\`define CHUNK_SIG2   "${DATA_DIR}/chunk_sig2.hex"
\`define CHUNK_NOISE0 "${DATA_DIR}/chunk_noise0.hex"
\`define WAVE_CSV     "${DATA_DIR}/sanity_wave.csv"
\`define RESULTS_TXT  "${DATA_DIR}/sanity_results.txt"
SVEOF
echo "      Written: $PATHS_SVH"

# ─── Step 3: Bender source list ──────────────────────────────────────────────
hr
echo "[3/5] Generating bender source list (target: simulation) ..."
bender script vivado -t simulation > "$BENDER_TCL"
N_FILES=$(grep -c 'add_files' "$BENDER_TCL" 2>/dev/null || echo 0)
echo "      $N_FILES file entries in bender output → ${BENDER_TCL}"

# Extract file paths from:  add_files -norecurse {/path/to/file.ext}
# Handles both single-file and potential multi-file lines.
extract_paths() {
    grep -oP '(?<=\{)[^}]+' "$BENDER_TCL" | tr -s ' ' '\n' | grep -v '^$'
}

VHDL_FILES=()
VLOG_FILES=()
SV_DEPS=()          # SV deps from bender (exclude our own TB)

while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    [[ "$path" == //* ]] && continue  # skip comment lines
    ext="${path##*.}"
    fname="${path##*/}"
    case "$ext" in
        vhd|vhdl)
            VHDL_FILES+=("$path") ;;
        v)
            VLOG_FILES+=("$path") ;;
        sv)
            # Skip the full testbench — it has hardcoded paths not valid here.
            [[ "$fname" == "tb_hilo_cnn_trigger.sv" ]] && continue
            # Skip tb_sanity.sv from bender list (we compile it separately).
            [[ "$fname" == "tb_sanity.sv" ]] && continue
            SV_DEPS+=("$path") ;;
    esac
done < <(extract_paths)

echo "      VHDL: ${#VHDL_FILES[@]}  Verilog: ${#VLOG_FILES[@]}  SV deps: ${#SV_DEPS[@]}"

# ─── Step 4: Compile ──────────────────────────────────────────────────────────
hr
echo "[4/5] Compiling ..."

# ── 4a. VHDL dependencies (from bender) ──
if [ ${#VHDL_FILES[@]} -gt 0 ]; then
    echo "      xvhdl (deps): ${#VHDL_FILES[@]} files ..."
    xvhdl -2008 \
          -work "$WORK" \
          --log "${LOG_DIR}/xvhdl_deps.log" \
          "${VHDL_FILES[@]}"
fi

# ── 4b. Verilog dependencies (HLS-generated CNN core, wrapper) ──
if [ ${#VLOG_FILES[@]} -gt 0 ]; then
    echo "      xvlog  (deps): ${#VLOG_FILES[@]} files ..."
    xvlog \
        -work "$WORK" \
        --log "${LOG_DIR}/xvlog_deps.log" \
        "${VLOG_FILES[@]}"
fi

# ── 4c. SV dependencies (from bender, if any) ──
if [ ${#SV_DEPS[@]} -gt 0 ]; then
    echo "      xvlog -sv (sv deps): ${#SV_DEPS[@]} files ..."
    xvlog -sv \
          -work "$WORK" \
          --log "${LOG_DIR}/xvlog_sv_deps.log" \
          "${SV_DEPS[@]}"
fi

# ── 4d. Our top-level VHDL design ──
# Bender may have already compiled these; recompiling is harmless and guarantees
# the latest version is in the library.
echo "      xvhdl (top): CNN_CHUNK_CAPTURE, HILO_CNN_TRIGGER, TB_WRAP ..."
xvhdl -2008 \
      -work "$WORK" \
      --log "${LOG_DIR}/xvhdl_top.log" \
      hw/rtl/CNN_CHUNK_CAPTURE.vhd \
      hw/rtl/HILO_CNN_TRIGGER.vhd \
      hw/sim/HILO_CNN_TRIGGER_TB_WRAP.vhd

# ── 4e. Testbench SV (tb_sanity.sv) ──
echo "      xvlog -sv (tb): tb_sanity.sv ..."
xvlog -sv \
      -work "$WORK" \
      --log "${LOG_DIR}/xvlog_tb.log" \
      hw/sim/tb_sanity.sv

# ─── Step 5: Elaborate + Simulate ────────────────────────────────────────────
hr
echo "[5/5] Elaborating and simulating ..."

echo "      xelab: ${WORK}.${TOP} → snapshot '${SNAP}' ..."
xelab \
    -debug typical \
    -L "$WORK" \
    "${WORK}.${TOP}" \
    --snapshot "$SNAP" \
    --log "${LOG_DIR}/xelab.log"

echo "      xsim:  running simulation ..."
xsim "$SNAP" \
    --runall \
    --log "${LOG_DIR}/xsim_run.log"

# ─── Post-simulation: check outputs ─────────────────────────────────────────
hr
echo "Checking outputs ..."
for f in sanity_wave.csv sanity_results.txt; do
    fpath="${DATA_DIR}/${f}"
    if [[ -f "$fpath" ]]; then
        N=$(wc -l < "$fpath")
        echo "  OK  $fpath  ($N lines)"
    else
        echo "  MISSING  $fpath  (simulation may have failed)"
    fi
done

# ─── Step 6: Plot results ─────────────────────────────────────────────────────
if [[ $SKIP_PLOT -eq 1 ]]; then
    hr
    echo "[SKIP] Plotting (--skip-plot set)."
    echo "       To plot manually:"
    echo "       python3 scripts/plot_sanity_results.py --data-dir hw/sim/sanity_data \\"
    echo "               --thresh ${THRESH} --hilo-window 10 --coinc-window 20 --bin-thr 1"
else
    hr
    echo "[6/6] Plotting results ..."
    python3 "${SCRIPT_DIR}/plot_sanity_results.py" \
        --data-dir "${DATA_DIR}" \
        --thresh   "$THRESH" \
        --hilo-window 10 \
        --coinc-window 20 \
        --bin-thr 1
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
hr
echo ""
echo "============================================================"
echo "  All done."
echo "  Simulation logs : $LOG_DIR/"
echo "  Data output     : $DATA_DIR/"
echo "  Plots           : $DATA_DIR/plots/"
echo "============================================================"
echo ""

# Print pass/fail from results file
if [[ -f "${DATA_DIR}/sanity_results.txt" ]]; then
    PASS=$(grep -v '^#' "${DATA_DIR}/sanity_results.txt" | awk -F',' '{s+=$NF} END{print s+0}')
    TOTAL=$(grep -cv '^#' "${DATA_DIR}/sanity_results.txt" || echo 0)
    echo "  Test result: ${PASS}/${TOTAL} PASSED"
    if [[ "$PASS" == "$TOTAL" && "$TOTAL" -gt 0 ]]; then
        echo "  ALL PASS ✓"
    else
        echo "  FAILURES — check ${DATA_DIR}/sanity_results.txt"
    fi
fi
echo ""
