#!/usr/bin/env bash
# =============================================================================
# run_thermal_sim.sh — Thermal noise simulation for HILO_CNN_TRIGGER
#
# Streams hilo-trigger thermal noise data through the full trigger pipeline
# and captures the first 3 chunks that pass L0_PRE_TRIG.
#
# Usage:
#   cd <project root>
#   source /path/to/Vivado/202X.X/settings64.sh
#   bash scripts/run_thermal_sim.sh [--skip-data] [--skip-plot]
#
#   --skip-data   Skip data preparation (stimulus.txt already exists).
#   --skip-plot   Skip plotting after simulation.
#
# Requirements:
#   Vivado (xvhdl, xvlog, xelab, xsim), bender, Python ≥ 3.8 (numpy, matplotlib, pandas)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SKIP_DATA=0
SKIP_PLOT=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-data) SKIP_DATA=1 ; shift ;;
        --skip-plot) SKIP_PLOT=1 ; shift ;;
        *) echo "Unknown option: $1 (valid: --skip-data, --skip-plot)"; exit 1 ;;
    esac
done

# ─── Fixed configuration ─────────────────────────────────────────────────────
THERMAL_DIR="/home/work1/Works/Hi-Lo-Trigger/analysis/data/thermal"
DATA_OUT="${ROOT}/hw/sim/thermal_data"
LOG_DIR="${ROOT}/logs/sim"
PATHS_SVH="${DATA_OUT}/thermal_paths.svh"
BENDER_TCL="${LOG_DIR}/bender_sources.tcl"
WORK="xil_defaultlib"
TOP="tb_thermal"
SNAP="tb_thermal_snapshot"

hr() { echo ""; echo "──────────────────────────────────────────────────────────────"; }

for tool in xvhdl xvlog xelab xsim bender; do
    command -v "$tool" &>/dev/null || {
        echo "ERROR: '$tool' not found in PATH."; exit 1
    }
done

mkdir -p "$LOG_DIR" "$DATA_OUT"
cd "$ROOT"

echo "============================================================"
echo "  HILO_CNN_TRIGGER Thermal Noise Simulation"
echo "  Root   : $ROOT"
echo "  Thermal: $THERMAL_DIR"
echo "  Output : $DATA_OUT"
echo "============================================================"

# ─── Step 1: Prepare stimulus ─────────────────────────────────────────────────
hr
if [[ $SKIP_DATA -eq 1 ]]; then
    echo "[SKIP] Data preparation."
    [[ -f "${DATA_OUT}/stimulus.txt" ]] || {
        echo "ERROR: ${DATA_OUT}/stimulus.txt not found. Run without --skip-data."; exit 1
    }
else
    echo "[1/6] Preparing thermal stimulus ..."
    python3 "${SCRIPT_DIR}/prepare_thermal_sim.py" \
        --data-dir "$THERMAL_DIR" \
        --out-dir  "$DATA_OUT"
fi

# Read 3σ threshold from metadata written by prepare_thermal_sim.py
THRESH=192
META="${DATA_OUT}/stim_meta.txt"
if [[ -f "$META" ]]; then
    HINT=$(grep thresh_3sigma_adc "$META" | awk '{print $2}')
    [[ -n "$HINT" ]] && THRESH="$HINT"
fi
echo "      Using threshold: ${THRESH} ADC counts (3σ)"

# ─── Step 2: Generate thermal_paths.svh ──────────────────────────────────────
hr
echo "[2/6] Writing thermal_paths.svh ..."
cat > "$PATHS_SVH" << SVEOF
// Auto-generated by run_thermal_sim.sh — do not edit.
\`define STIMULUS_TXT    "${DATA_OUT}/stimulus.txt"
\`define CHUNK_WAVE_CSV  "${DATA_OUT}/chunk_wave.csv"
\`define CNN_RESULTS_TXT "${DATA_OUT}/cnn_results.txt"
SVEOF

# ─── Step 3: Bender source list ──────────────────────────────────────────────
hr
echo "[3/6] Generating bender source list ..."
bender script vivado -t simulation > "$BENDER_TCL"

extract_paths() {
    local tcl_root
    tcl_root=$(grep '^set ROOT' "$BENDER_TCL" | sed 's/^set ROOT "\(.*\)"/\1/')
    if [[ -z "$tcl_root" ]]; then
        grep -oP '/[^\s"\\]+\.(vhd|vhdl|v|sv|vh)\b' "$BENDER_TCL"; return
    fi
    grep -oP '(?<=\$ROOT)/[^\s\\]+\.(vhd|vhdl|v|sv|vh)\b' "$BENDER_TCL" \
        | sed "s|^|${tcl_root}|"
}

VHDL_FILES=(); VLOG_FILES=(); VLOG_INC_DIRS=(); SV_DEPS=()
while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    ext="${path##*.}"; fname="${path##*/}"
    case "$ext" in
        vhd|vhdl) VHDL_FILES+=("$path") ;;
        vh) dir="$(dirname "$path")"
            [[ " ${VLOG_INC_DIRS[*]} " != *" ${dir} "* ]] && VLOG_INC_DIRS+=("$dir") ;;
        v) VLOG_FILES+=("$path") ;;
        sv)
            [[ "$fname" == "tb_hilo_cnn_trigger.sv" ]] && continue
            [[ "$fname" == "tb_sanity.sv"            ]] && continue
            [[ "$fname" == "tb_thermal.sv"           ]] && continue
            SV_DEPS+=("$path") ;;
    esac
done < <(extract_paths)

# ─── Step 4: Compile ──────────────────────────────────────────────────────────
hr
echo "[4/6] Compiling ..."

[ ${#VHDL_FILES[@]} -gt 0 ] && \
    xvhdl -2008 -work "$WORK" --log "${LOG_DIR}/xvhdl_deps.log" "${VHDL_FILES[@]}"

if [ ${#VLOG_FILES[@]} -gt 0 ]; then
    INC_FLAGS=()
    for d in "${VLOG_INC_DIRS[@]}"; do INC_FLAGS+=(-i "$d"); done
    xvlog -work "$WORK" --log "${LOG_DIR}/xvlog_deps.log" "${INC_FLAGS[@]}" "${VLOG_FILES[@]}"
fi

[ ${#SV_DEPS[@]} -gt 0 ] && \
    xvlog -sv -work "$WORK" --log "${LOG_DIR}/xvlog_sv_deps.log" "${SV_DEPS[@]}"

xvhdl -2008 -work "$WORK" --log "${LOG_DIR}/xvhdl_top.log" \
    hw/rtl/CNN_CHUNK_CAPTURE.vhd \
    hw/rtl/HILO_CNN_TRIGGER.vhd \
    hw/sim/HILO_CNN_TRIGGER_TB_WRAP.vhd

xvlog -sv -work "$WORK" --log "${LOG_DIR}/xvlog_tb_thermal.log" \
    hw/sim/tb_thermal.sv

# ─── Step 5: Elaborate + Simulate ────────────────────────────────────────────
hr
echo "[5/6] Elaborating and simulating ..."

xelab \
    -debug typical -L "$WORK" "${WORK}.${TOP}" \
    --snapshot "$SNAP" \
    -generic_top "P_THRESH=${THRESH}" \
    --log "${LOG_DIR}/xelab_thermal.log"

xsim "$SNAP" --runall --log "${LOG_DIR}/xsim_thermal.log"

# ─── Check outputs ────────────────────────────────────────────────────────────
hr
echo "Outputs:"
for f in chunk_wave.csv cnn_results.txt; do
    fp="${DATA_OUT}/${f}"
    [[ -f "$fp" ]] && echo "  OK  $fp  ($(wc -l < "$fp") lines)" \
                   || echo "  MISSING  $fp"
done

# ─── Step 6: Plot ─────────────────────────────────────────────────────────────
if [[ $SKIP_PLOT -eq 0 ]]; then
    hr
    echo "[6/6] Plotting ..."
    python3 "${SCRIPT_DIR}/plot_thermal_results.py" \
        --data-dir "$DATA_OUT" \
        --thresh   "$THRESH"
fi

hr
echo ""
echo "Done. Plots: ${DATA_OUT}/plots/"
if [[ -f "${DATA_OUT}/cnn_results.txt" ]]; then
    echo ""
    grep -v '^#' "${DATA_OUT}/cnn_results.txt" | awk -F',' \
        '{printf "  chunk %s : score=%s\n", $1, $5}'
fi
echo ""
